apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  namespace: test
  name: myvmi 
  labels:
      kubevirt.io/size: small
      kubevirt.io/domain: myvmi
spec:
  terminationGracePeriodSeconds: 5
  domain:
    resources:
      requests:
        memory: 1536M
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: cloudinitdisk
        disk:
          bus: virtio
  volumes:
    - name: containerdisk
      containerDisk:
        image: mjschmidt/centos:7-x86_64-genericcloud-1907
    - name: cloudinitdisk
      cloudInitNoCloud: 
        userDataBase64: I2Nsb3VkLWNvbmZpZwoKcGFja2FnZV91cGdyYWRlOiB0cnVlCgpwYWNrYWdlczoKICAtIGdpdAoKI2lmIHNvbWV0aGluZyBnb2VzIHdyb25nIHRoaXMgaXMgdGhlIGlzc3VlCndyaXRlX2ZpbGVzOgotICAgY29udGVudDogfAogICAgICAgICMgTXkgbmV3IC9ldGMvc3lzY29uZmlnL3NhbWJhIGZpbGUKICAgICAgICAjCiAgICAgICAgIyAgICAgICAgIFNNQkRPUFRJT05TPSItRCIKICAgIG93bmVyOiByb290OnJvb3QKICAgIHBhdGg6IC9ldGMvc3lzY29uZmlnLzY0Yml0X3N0cnN0cl92aWFfNjRiaXRfc3Ryc3RyX3NzZTJfdW5hbGlnbmVkCgp1c2VyczoKICAtIG5hbWU6IGNlbnRvcwogICAgZ2Vjb3M6IGNlbnRvcwogICAgcGFzc3dvcmQ6IHBhc3N3b3JkCiAgICBsb2NrLXBhc3N3ZDogZmFsc2UKICAgIHN1ZG86IEFMTD0oQUxMKSBOT1BBU1NXRDpBTEwKICAgIHNzaF9hdXRob3JpemVkX2tleXM6CiAgICAgIC0gc3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBQkpRQUFBUUVBcjhjbFBNMmFoS0JMY1pwMXNoNysrVWxyUEgvRkJpREU4dEtidzRvRmxGa1pBRDVRU0F5dkhJKzRKTXFCNkZlZkJQOVRtOTY5d3FQajVJOVJCdHFjSTFmVFFWNnZlUitESjdid0hySWdYcnFXWXFMYWp1VkZzQWdVWDk2eHZMOEY0NmJvK2tXQmsxL2NJLzdxTFc4L3I1eXQrSFJvMlFoS0lWeXF4YWl3b2hkSThhQUhVWlVEdUx0c2pabDNsNjI1RGo5ZUZDUUUzZDNpakMwZUdTOHp0UEhxSVk0ZjhvbTFCdHlyYXlwQ0dUVW9pSUpVR2lKZXZnNjBFK2w0WGgxRTRtOTVwSGdDaVRJM1FpZngwOS82Zm1vSUZMZitqcTdxL0tIeDEvTGxTaUJDNzBTSm5pTnl3aHR5Zng2QU1RN0FCQytSUk1Gem5YOWVvckp3QzZMSnBRPT0gcnNhLWtleS0yMDE4MTEwOAogIC0gbmFtZTogbWpzY2htMwogICAgZ2Vjb3M6IG1qc2NobTMKICAgIGxvY2stcGFzc3dkOiBmYWxzZQogICAgc3VkbzogQUxMPShBTEwpIE5PUEFTU1dEOkFMTAogICAgc3NoX2F1dGhvcml6ZWRfa2V5czoKICAgICAgLSBzc2gtcnNhIEFBQUFCM056YUMxeWMyRUFBQUFCSlFBQUFRRUFyOGNsUE0yYWhLQkxjWnAxc2g3KytVbHJQSC9GQmlERTh0S2J3NG9GbEZrWkFENVFTQXl2SEkrNEpNcUI2RmVmQlA5VG05Njl3cVBqNUk5UkJ0cWNJMWZUUVY2dmVSK0RKN2J3SHJJZ1hycVdZcUxhanVWRnNBZ1VYOTZ4dkw4RjQ2Ym8ra1dCazEvY0kvN3FMVzgvcjV5dCtIUm8yUWhLSVZ5cXhhaXdvaGRJOGFBSFVaVUR1THRzalpsM2w2MjVEajllRkNRRTNkM2lqQzBlR1M4enRQSHFJWTRmOG9tMUJ0eXJheXBDR1RVb2lJSlVHaUpldmc2MEUrbDRYaDFFNG05NXBIZ0NpVEkzUWlmeDA5LzZmbW9JRkxmK2pxN3EvS0h4MS9MbFNpQkM3MFNKbmlOeXdodHlmeDZBTVE3QUJDK1JSTUZ6blg5ZW9ySndDNkxKcFE9PSByc2Eta2V5LTIwMTgxMTA4IAo=
