apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: centos 
spec:
  running: false
  template:
    metadata:
      labels: 
        kubevirt.io/size: small
        kubevirt.io/domain: centos
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: vda
            name: rootfs
          - disk:
              bus: vdb
            name: cloudinit
          interfaces:
          - name: default
            bridge: {}
        resources:
          requests:
            memory: 1536M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: rootfs
          containerDisk:
            image: mjschmidt/centos:7-x86_64-genericcloud-1907
        - name: cloudinit
          cloudInitNoCloud:
            userDataBase64: 
