{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubevirt-vm.serviceAccountName" . }}
  labels:
{{ include "kubevirt-vm.labels" . | nindent 4 }}
{{- end -}}
