{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pvc-builder.serviceAccountName" . }}
  labels:
{{ include "pvc-builder.labels" . | nindent 4 }}
{{- end -}}
