apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  namespace: mjschm3
  name: myvmi 
  labels:
      kubevirt.io/size: small
      kubevirt.io/domain: myvmi
spec:
  terminationGracePeriodSeconds: 5
  domain:
    resources:
      requests:
        memory: 1536M
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: cloudinitdisk
        disk:
          bus: virtio
  volumes:
    - name: containerdisk
      containerDisk:
        image: mjschmidt/centos:7-x86_64-genericcloud-1907
    - name: cloudinitdisk
      cloudInitNoCloud: 
        userDataBase64: I2Nsb3VkLWNvbmZpZwoKI3BhY2thZ2VfdXBncmFkZTogdHJ1ZQoKI3BhY2thZ2VzOgojICAtIGdpdAoKI2lmIHNvbWV0aGluZyBnb2VzIHdyb25nIHRoaXMgaXMgdGhlIGlzc3VlCndyaXRlX2ZpbGVzOgotICAgY29udGVudDogfAogICAgICAgICMgTXkgbmV3IC9ldGMvc3lzY29uZmlnL3NhbWJhIGZpbGUKICAgICAgICAjCiAgICAgICAgIyAgICAgICAgIFNNQkRPUFRJT05TPSItRCIKICAgIG93bmVyOiByb290OnJvb3QKICAgIHBhdGg6IC9ldGMvc3lzY29uZmlnLzY0Yml0X3N0cnN0cl92aWFfNjRiaXRfc3Ryc3RyX3NzZTJfdW5hbGlnbmVkCgp1c2VyczoKICAtIG5hbWU6IGNlbnRvcwogICAgZ2Vjb3M6IGNlbnRvcwogICAgcGFzc3dvcmQ6IHBhc3N3b3JkCiAgICBsb2NrLXBhc3N3ZDogZmFsc2UKICAgIHN1ZG86IEFMTD0oQUxMKSBOT1BBU1NXRDpBTEwKICAgIHNzaF9hdXRob3JpemVkX2tleXM6CiAgICAgIC0gc3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBQkpRQUFBUUVBcjhjbFBNMmFoS0JMY1pwMXNoNysrVWxyUEgvRkJpREU4dEtidzRvRmxGa1pBRDVRU0F5dkhJKzRKTXFCNkZlZkJQOVRtOTY5d3FQajVJOVJCdHFjSTFmVFFWNnZlUitESjdid0hySWdYcnFXWXFMYWp1VkZzQWdVWDk2eHZMOEY0NmJvK2tXQmsxL2NJLzdxTFc4L3I1eXQrSFJvMlFoS0lWeXF4YWl3b2hkSThhQUhVWlVEdUx0c2pabDNsNjI1RGo5ZUZDUUUzZDNpakMwZUdTOHp0UEhxSVk0ZjhvbTFCdHlyYXlwQ0dUVW9pSUpVR2lKZXZnNjBFK2w0WGgxRTRtOTVwSGdDaVRJM1FpZngwOS82Zm1vSUZMZitqcTdxL0tIeDEvTGxTaUJDNzBTSm5pTnl3aHR5Zng2QU1RN0FCQytSUk1Gem5YOWVvckp3QzZMSnBRPT0gcnNhLWtleS0yMDE4MTEwOCAKICAtIG5hbWU6IG1qc2NobWlkdAogICAgZ2Vjb3M6IG1qc2NobWlkdAogICAgbG9jay1wYXNzd2Q6IGZhbHNlCiAgICBzdWRvOiBBTEw9KEFMTCkgTk9QQVNTV0Q6QUxMCiAgICBzc2hfYXV0aG9yaXplZF9rZXlzOgogICAgICAtIHNzaC1yc2EgQUFBQUIzTnphQzF5YzJFQUFBQUJKUUFBQVFFQXI4Y2xQTTJhaEtCTGNacDFzaDcrK1VsclBIL0ZCaURFOHRLYnc0b0ZsRmtaQUQ1UVNBeXZISSs0Sk1xQjZGZWZCUDlUbTk2OXdxUGo1STlSQnRxY0kxZlRRVjZ2ZVIrREo3YndIcklnWHJxV1lxTGFqdVZGc0FnVVg5Nnh2TDhGNDZibytrV0JrMS9jSS83cUxXOC9yNXl0K0hSbzJRaEtJVnlxeGFpd29oZEk4YUFIVVpVRHVMdHNqWmwzbDYyNURqOWVGQ1FFM2QzaWpDMGVHUzh6dFBIcUlZNGY4b20xQnR5cmF5cENHVFVvaUlKVUdpSmV2ZzYwRStsNFhoMUU0bTk1cEhnQ2lUSTNRaWZ4MDkvNmZtb0lGTGYranE3cS9LSHgxL0xsU2lCQzcwU0puaU55d2h0eWZ4NkFNUTdBQkMrUlJNRnpuWDllb3JKd0M2TEpwUT09IHJzYS1rZXktMjAxODExMDgK 
